RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "CloudTrail Logs Monitoring Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = "https://code.amazon.com/packages/Aws-workshop-template/blobs/master/--/workshop/content/"
  description = "Observability Workshop"
  author = "Imaya Kumar Jagannathan"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-trash-alt'></i> Environment cleanup"
identifier = "Cleanup"
url = "/_cleanup.html"
weight = 10


[Languages]
[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fb fa-github'></i> Get the source code"
identifier = "repo"
url = "https://github.com/awstiber/cloudwatch-logs-code"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Report an Issue or feature request"
identifier = "issue"
url = "https://github.com/awstiber/cloudwatch-logs-code/issues/new"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-building'></i> Are you an AWS employee?"
identifier = "collaborate"
url = "/_collaborate.html"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-user-friends'></i> Contributors"
identifier = "contributors"
url = "/_contributors.html"
weight = 41

[Languages.en]
title = "Observability Workshop"
weight = 50
languageName = "English"


