RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Observability Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
  editURL = "https://code.amazon.com/packages/Aws-workshop-template/blobs/master/--/workshop/content/"
  description = "Observability Workshop"
  author = "Imaya Kumar Jagannathan"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-trash-alt'></i> Environment cleanup"
identifier = "Cleanup"
url = "/_cleanup.html"
weight = 10

[[Languages.ja.menu.shortcuts]]
name = "<i class='fas fa-trash-alt'></i> ワークショップ環境の削除"
identifier = "クリーンアップ"
url = "/_cleanup.html"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-trash-alt'></i> Liberar recursos"
identifier = "Limpieza"
url = "/_cleanup.html"
weight = 10

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-trash-alt'></i> 리소스 및 환경 정리"
identifier = "Cleanup"
url = "/_cleanup.html"
weight = 10

[Languages]
[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fb fa-github'></i> Get the source code"
identifier = "repo"
url = "https://github.com/aws-samples/one-observability-demo"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Report an Issue or feature request"
identifier = "issue"
url = "https://github.com/aws-samples/one-observability-demo/issues/new"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-building'></i> Are you an AWS employee?"
identifier = "collaborate"
url = "/_collaborate.html"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-user-friends'></i> Contributors"
identifier = "contributors"
url = "/_contributors.html"
weight = 41

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fb fa-github'></i> Código Fuente"
identifier = "repo"
url = "https://github.com/aws-samples/one-observability-demo"
weight = 20

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> Reportar un problema"
identifier = "issue"
url = "https://github.com/aws-samples/one-observability-demo/issues/new"
weight = 30

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-building'></i> ¿Eres empleado de AWS?"
identifier = "collaborate"
url = "/_collaborate.html"
weight = 40

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-user-friends'></i> Colaboradores"
identifier = "contributors"
url = "/_contributors.html"
weight = 41

[[Languages.ko.menu.shortcuts]]
name = "<i class='fab fa-fb fa-github'></i> 소스코드 보기"
identifier = "repo"
url = "https://github.com/aws-samples/one-observability-demo"
weight = 20

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-bug'></i> 이슈, 기능 요청하기"
identifier = "issue"
url = "https://github.com/aws-samples/one-observability-demo/issues/new"
weight = 30

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-building'></i> AWS 직원이신가요?"
identifier = "collaborate"
url = "/_collaborate.html"
weight = 40

[[Languages.ko.menu.shortcuts]]
name = "<i class='fas fa-user-friends'></i> Contributors"
identifier = "contributors"
url = "/_contributors.html"
weight = 41

[Languages.en]
title = "Observability Workshop"
weight = 50
languageName = "English"

[Languages.ja]
title = "Observability Workshop"
weight = 50
languageName = "Japanese"

[Languages.es]
title = "Taller de Observabilidad"
weight = 50
languageName = "Español"

[Languages.ko]
title = "Observability Workshop"
weight = 50
languageName = "한국어"
